
services:
  reverse-proxy:
    container_name: reverse-proxy
    build: .
    image: reverse-proxy:latest
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - pbs-state-website
    depends_on:
      - frontend

  frontend:
    container_name: pbs-bahamas-frontend
    image: quincyarthur242/pbs-bahamas-state-frontend:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - pbs-state-website
    depends_on:
      - backend

  backend:
    container_name: pbs-bahamas-backend
    image: quincyarthur242/pbs-bahamas-state-backend:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - '1337:1337'
    networks:
      - pbs-state-website
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - '5432:5432'
    networks:
      - pbs-state-website

volumes:
  strapi-data:

networks:
  pbs-state-website:
    name: PBS-State-Website
    driver: bridge
